title: Amo San Martino
description: >
  A geniuine Italian town minutes from the Adriatic Sea
baseurl: ""
url: "http://amosanmartino.com"

twitter_username: gdsmip
facebook_username: San-Martino-In-Pensilis-370969602199

markdown: kramdown
