title: Amo San Martino
description: >
  A geniuine Italian town minutes from the Adriatic Sea
baseurl: "/"
url: "http://amosanmartino.com"

twitter_username: SBootstrap
github_username:  BlackrockDigital
facebook_username: StartBootstrap

address_street: 3034 Melrose Place
address_city: Beverly Hills
address_state: CA
address_zip: 90201

markdown: kramdown
